# ---------- Build stage ----------
FROM node:16-bullseye AS builder

WORKDIR /usr/src/app

# Install deps (including dev deps for build)
COPY package*.json ./
# Using npm install instead of npm ci because the lockfile
# was generated by a newer npm (lockfileVersion 3) than the
# npm version bundled with Node 14, which makes npm ci fail.
RUN npm install

# Copy source
COPY . .

# Build assets (React, TS, etc.)
RUN npm run build


# ---------- Production stage ----------
FROM node:16-bullseye-slim

WORKDIR /usr/src/app

# Image resizing dependency (replacement for sharp)
RUN apt-get update \
  && apt-get install -y --no-install-recommends imagemagick \
  && rm -rf /var/lib/apt/lists/*

# Copy built files (and node_modules) from builder stage
COPY --from=builder /usr/src/app ./

ENV NODE_ENV=production

EXPOSE 3666

CMD ["npm", "start"]